version: "3.7"

services:

    controller:
        build:
            context: .
            dockerfile: ./netpalm_controller_dockerfile

        command: gunicorn -c gunicorn.conf.py netpalm_controller:app
        environment:
            - NET_TEXTFSM=/usr/local/lib/python3.8/site-packages/ntc_templates/templates/
            - NETPALM_CONFIG=/code/config.json
            - NETPALM_LOG_CONFIG_FILENAME=/code/log-config.yml
#        volumes:
#            - .:/code
        ports:
            - "9000:9000"
        networks:
            - "netpalm-network"
        depends_on:
            - redis
            - cisgo

    second-ctrlr:  # using --scale doesn't work on controllers because they all want to own port 9000
        image: netpalm_netpalm-controller
        command: gunicorn -c gunicorn.conf.py netpalm_controller:app
        environment:
            - NET_TEXTFSM=/usr/local/lib/python3.8/site-packages/ntc_templates/templates/
            - NETPALM_CONFIG=/code/config.json
            - NETPALM_LOG_CONFIG_FILENAME=/code/log-config.yml
        #        volumes:
        #            - .:/code
        ports:
            - "9001:9000"
        networks:
            - "netpalm-network"
        depends_on:
            - redis

    worker-pinned:
        image: netpalm_netpalm-controller
        command: python3 netpalm_pinned_worker.py
        environment:
            - NET_TEXTFSM=/usr/local/lib/python3.8/site-packages/ntc_templates/templates/
            - NETPALM_CONFIG=/code/config.json
            - NETPALM_LOG_CONFIG_FILENAME=/code/log-config.yml
        depends_on:
            - redis
        networks:
            - "netpalm-network"

    worker-fifo:
        image: netpalm_netpalm-controller
        command: python3 netpalm_fifo_worker.py
        environment:
            - NET_TEXTFSM=/usr/local/lib/python3.8/site-packages/ntc_templates/templates/
            - NETPALM_CONFIG=/code/config.json
            - NETPALM_LOG_CONFIG_FILENAME=/code/log-config.yml
        depends_on:
            - redis
        networks:
            - "netpalm-network"

    redis:
        image: redis
        command: redis-server --requirepass Red1zp4ww0rd_

        networks:
            - "netpalm-network"

    cisgo:
        build:
            context: ..\cisgo-ios
        #            dockerfile: Dockerfile
        ports:
            - "10005:10005"
        networks:
            - "netpalm-network"

networks:
    netpalm-network:
        name: "netpalm-network"
