---
version: 1
formatters:
  simple:
    # format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    format: '[%(asctime)s:%(name)s:%(funcName)s:%(levelname)s] %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  urllib3:
    level: WARN
  asyncio:
    level: INFO
  backend:
    level: INFO
  netmiko:
    level: WARN
  paramiko:
    level: WARN
  rq.worker:
    level: WARN
  rq:
    level: WARN

root:
  level: DEBUG
  handlers: [console]

disable_existing_loggers: False
